root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/media-gate"
  cmd = "go build -o ./tmp/media-gate ./cmd/server/"
  delay = 1000
  exclude_dir = ["tmp", "node_modules"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go", "yaml"]
  kill_delay = 500

[log]
  time = false
